[tool]
id = "com.loosewire.lightious"
label = "Lightious"
versionCode = 5
versionName = "0.3.2"
permissions = ["android.permission.INTERNET", "android.permission.ACCESS_NETWORK_STATE", "android.permission.WAKE_LOCK"]
capabilities = ["detached-audio"]
serverPackage = "com.lightos"
orientation = "portrait"
